#!/usr/bin/env python3
"""
create_panning_animation.py

Create panning animations from wide or tall PNG images.
Designed for PowerPoint 16:9 widescreen presentations.

Input format:
- Main input: PNG only. Use KaryoScope_plot_reads.py --format png to generate.
- Legend: PNG or SVG (small SVGs convert easily via rsvg-convert).

Note on SVG performance: Large SVGs (100+ MB, 2M+ elements) exceed rsvg-convert's
element limits and require slow Playwright/Chromium fallback rendering. For best
performance, generate PNG directly with plot_reads.py --format png --png-scale 8.0.

Zoom modes:
- fixed: classic seamless looping pan with optional crop ratio
- adaptive: dynamically zooms to keep tallest visible read filling viewport

Duration modes:
- --duration N: fixed duration in seconds
- --num-reads N --reads-per-second R: auto-calculate from read count (default)

Usage:
    # Fixed zoom, auto-duration from reads
    python create_panning_animation.py \\
        --input reads.png --output pan.mp4 \\
        --num-reads 35412 --reads-per-second 30

    # Adaptive zoom with legend
    python create_panning_animation.py \\
        --input reads.png --output pan.mp4 \\
        --zoom adaptive --num-reads 35412 \\
        --legend legend.svg
"""

import argparse
import math
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

# Try to import cv2 for faster resizing
try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False

# Allow very large images
Image.MAX_IMAGE_PIXELS = None

# ─── SVG helpers (for legend conversion only) ────────────────────────────────

def get_svg_dimensions(svg_path):
    """Parse SVG width and height from file header."""
    with open(svg_path) as f:
        header = f.read(4000)
    w_match = re.search(r'width="([\d.]+)"', header)
    h_match = re.search(r'height="([\d.]+)"', header)
    if w_match and h_match:
        return float(w_match.group(1)), float(h_match.group(1))
    return None, None


def svg_to_png(svg_path, height=None, width=None):
    """Convert SVG to temporary PNG using rsvg-convert.

    Note: This is used only for legend SVG conversion. For main input images,
    use PNG files generated by plot_reads.py --format png.

    Args:
        svg_path: Path to SVG file
        height: Target height in pixels (optional)
        width: Target width in pixels (optional)

    Returns (temp_png_path, scale_factor).
    """
    svg_w, svg_h = get_svg_dimensions(svg_path)

    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    tmp.close()

    print(f"  Converting SVG → PNG: {os.path.basename(svg_path)}")
    if svg_w and svg_h:
        print(f"    SVG dimensions: {svg_w:.0f} x {svg_h:.0f}")
    if height:
        print(f"    Target height: {height}")
    if width:
        print(f"    Target width: {width}")

    # Use rsvg-convert (suitable for small legend SVGs)
    cmd = ["rsvg-convert", "-o", tmp.name]
    if height:
        cmd.extend(["-h", str(height)])
    if width:
        cmd.extend(["-w", str(width)])
    cmd.append(svg_path)

    try:
        env = os.environ.copy()
        env["RSVG_MAX_LOADED_ELEMENTS"] = "100000000"
        subprocess.run(cmd, check=True, capture_output=True, text=True, env=env)
    except subprocess.CalledProcessError as e:
        raise RuntimeError(
            f"rsvg-convert failed for {svg_path}. "
            "Legend SVGs should be small enough for rsvg-convert. "
            f"Error: {e.stderr}"
        )

    # Calculate scale factor
    if width and svg_w:
        scale = width / svg_w
    elif height and svg_h:
        scale = height / svg_h
    else:
        scale = 1.0

    img = Image.open(tmp.name)
    print(f"    PNG dimensions: {img.size[0]} x {img.size[1]}")
    img.close()

    return tmp.name, scale


def ensure_png(path, svg_height=None, svg_width=None):
    """Return (png_path, is_temp, scale_factor).

    If upscaling fails (element limits), falls back to native resolution.
    """
    if path.lower().endswith(".svg"):
        try:
            png_path, scale = svg_to_png(path, height=svg_height, width=svg_width)
            return png_path, True, scale
        except RuntimeError as e:
            # If we were trying to upscale and it failed, try native resolution
            if svg_height or svg_width:
                print(f"    Upscaling failed, falling back to native resolution...")
                png_path, scale = svg_to_png(path, height=None, width=None)
                return png_path, True, scale
            raise
    return path, False, 1.0


# ─── Font / scale bar helpers ────────────────────────────────────────────────

def _load_font(size=14):
    """Load Basic Sans font with fallback."""
    font_dir = Path.home() / "Documents" / "Barthel-Custom-Powerpoint-Theme" / "fonts"
    font_path = font_dir / "BasicSans-Regular.otf"
    if font_path.exists():
        return ImageFont.truetype(str(font_path), size)
    try:
        return ImageFont.truetype("Arial", size)
    except (OSError, IOError):
        return ImageFont.load_default()


def _nice_scale_value(bp):
    """Round bp to a nice human-readable scale bar value."""
    nice = [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000, 200000]
    for v in nice:
        if v >= bp * 0.4:
            return v
    return nice[-1]


def draw_dynamic_scale_bar(frame, zoom, ratio, padding_x=20, padding_y=20,
                           target_height=80, text_color=(255, 255, 255)):
    """Draw a scale bar on a video frame that reflects the current zoom level.

    The bar has a fixed approximate visual height; the label snaps to a nice
    round number of bp.
    """
    draw_ctx = ImageDraw.Draw(frame)

    # Physical length represented by target_height viewport pixels
    source_px = target_height / zoom
    bp = source_px / ratio
    nice_bp = _nice_scale_value(bp)

    # Actual visual height for the nice value
    actual_source_px = nice_bp * ratio
    actual_height = int(actual_source_px * zoom)
    actual_height = max(10, min(actual_height, frame.height - 2 * padding_y))

    bar_x = padding_x
    bar_y = padding_y

    # Vertical bar
    draw_ctx.rectangle(
        [bar_x, bar_y, bar_x + 3, bar_y + actual_height], fill=text_color
    )
    # Ticks
    draw_ctx.line([(bar_x - 3, bar_y), (bar_x + 6, bar_y)], fill=text_color, width=1)
    draw_ctx.line(
        [(bar_x - 3, bar_y + actual_height), (bar_x + 6, bar_y + actual_height)],
        fill=text_color,
        width=1,
    )

    label = f"{nice_bp // 1000} Kbp" if nice_bp >= 1000 else f"{nice_bp} bp"
    font = _load_font(14)
    draw_ctx.text((bar_x + 10, bar_y + 2), label, fill=text_color, font=font)


# ─── Adaptive zoom helpers ───────────────────────────────────────────────────

def detect_content_heights(img_array, top_margin, left_margin=0, bg_color="black"):
    """Vectorised column-wise content height detection below *top_margin*.

    Args:
        img_array: numpy array of shape (H, W, 3)
        top_margin: rows above this are ignored (header area)
        left_margin: columns before this are set to 0 (y-axis labels area)
        bg_color: "black" or "white" background

    Returns:
        1D array of heights per column
    """
    h, w, _ = img_array.shape
    if top_margin >= h:
        return np.zeros(w, dtype=np.float64)

    region = img_array[top_margin:]
    is_content = (
        np.any(region != 0, axis=2)
        if bg_color == "black"
        else np.any(region != 255, axis=2)
    )

    row_indices = np.arange(is_content.shape[0]).reshape(-1, 1)
    content_rows = np.where(is_content, row_indices, -1)
    max_rows = content_rows.max(axis=0)
    heights = np.where(max_rows >= 0, max_rows + 1, 0).astype(np.float64)

    # Zero out the left margin (y-axis labels, not actual reads)
    if left_margin > 0:
        heights[:left_margin] = 0

    return heights


def build_height_profile(raw_heights):
    """Smooth and enforce monotonically non-increasing envelope.

    The profile should smoothly decrease (or stay flat) as we pan right,
    reflecting reads sorted by decreasing length.
    """
    profile = raw_heights.copy()

    # Find first non-zero index (content start)
    nonzero_idx = np.nonzero(profile > 0)[0]
    if len(nonzero_idx) == 0:
        return profile  # No content found

    first_content = nonzero_idx[0]

    # Forward-fill zeros within content region (fills spacing gaps between reads)
    last = 0.0
    for i in range(first_content, len(profile)):
        if profile[i] > 0:
            last = profile[i]
        elif last > 0:
            profile[i] = last

    # Enforce monotonically non-increasing starting from first content
    # (Since reads are sorted longest→shortest, heights should only decrease)
    for i in range(first_content + 1, len(profile)):
        if profile[i] > profile[i - 1]:
            profile[i] = profile[i - 1]

    # Fill leading zeros with the first content height (for smooth start)
    if first_content > 0:
        profile[:first_content] = profile[first_content]

    return profile


def _find_content_bounds(profile):
    """Return (first_x, last_x) with non-zero profile values."""
    nonzero = np.nonzero(profile > 0)[0]
    if len(nonzero) == 0:
        return 0, len(profile)
    return int(nonzero[0]), int(nonzero[-1]) + 1


# ─── Adaptive zoom panning ───────────────────────────────────────────────────

def _smooth_profile(profile, window=100):
    """Apply exponential moving average for smoother zoom transitions."""
    smoothed = np.zeros_like(profile)
    alpha = 2 / (window + 1)
    smoothed[0] = profile[0]
    for i in range(1, len(profile)):
        smoothed[i] = alpha * profile[i] + (1 - alpha) * smoothed[i - 1]
    return smoothed


# ─── Strip-based pre-rendering ────────────────────────────────────────────────

def compute_strip_zoom_levels(profile, num_strips, available_height, max_zoom, content_padding=10):
    """Divide SVG into strips, compute max zoom needed for each.

    Args:
        profile: Content height profile (1D array, height per x-position)
        num_strips: Number of strips to divide into
        available_height: Viewport height available for content
        max_zoom: Maximum zoom factor
        content_padding: Padding around content

    Returns:
        List of (x_start, x_end, zoom_level) tuples
    """
    total_width = len(profile)
    strip_width = max(1, total_width // num_strips)
    strips = []

    for i in range(num_strips):
        x_start = i * strip_width
        x_end = min((i + 1) * strip_width, total_width)
        if x_start >= total_width:
            break

        # Max content height in this strip (use max to ensure we render enough)
        strip_profile = profile[x_start:x_end]
        if len(strip_profile) == 0:
            continue
        max_content = max(strip_profile.max(), 20)  # minimum content height

        # Zoom needed to fill available_height
        zoom = min(available_height / (max_content + content_padding), max_zoom)
        strips.append((x_start, x_end, zoom))

    return strips


# ─── PNG-based panning functions ──────────────────────────────────────────────

def create_adaptive_horizontal_panning(
    input_path,
    output_path,
    duration,
    fps,
    viewport_width,
    viewport_height,
    legend_path,
    background,
    top_margin,
    left_margin,
    ratio,
    max_zoom,
    scale_bar_padding,
    scale_bar_width=100,
    zoom_smoothing=200,
    uniform_zoom=True,
    top_bias=0.0,
):
    """Horizontal panning with adaptive zoom.

    Key features:
    - Uniform zoom (if enabled): zooms both horizontally and vertically together
    - Smooth zoom transitions via exponential moving average
    - Scale bar in dedicated left margin (not overlapping content)
    - Legend composited below panning area

    Args:
        uniform_zoom: If True, apply same zoom to both dimensions.
                      If False, only zoom vertically (legacy behavior).
    """

    print("Creating adaptive-zoom horizontal panning animation")
    print(f"  Input:    {input_path}")
    print(f"  Output:   {output_path}")
    print(f"  Duration: {duration:.1f}s  FPS: {fps}")
    print(f"  Viewport: {viewport_width} x {viewport_height}")

    # Load image into numpy array
    img = Image.open(input_path)
    img_array = np.array(img)
    img_h, img_w = img_array.shape[:2]
    print(f"  Image:    {img_w} x {img_h}")

    # Content height profile
    print(f"  Detecting content heights (top_margin={top_margin}, left_margin={left_margin})…")
    raw_heights = detect_content_heights(img_array, top_margin, left_margin, background)
    profile = build_height_profile(raw_heights)

    # Smooth the profile for gradual zoom transitions
    if zoom_smoothing > 0:
        profile = _smooth_profile(profile, window=zoom_smoothing)
        print(f"  Applied zoom smoothing (window={zoom_smoothing})")

    max_c = profile.max()
    nonzero = profile[profile > 0]
    min_c = nonzero.min() if len(nonzero) else 1
    print(f"  Content height range: {max_c:.0f} – {min_c:.0f} px (source)")

    content_start, content_end = _find_content_bounds(profile)
    print(f"  Content x-range: {content_start} – {content_end}")

    # Allocate layout:
    # [scale_bar_width] [panning_area] = viewport_width
    panning_width = viewport_width - scale_bar_width
    if panning_width < 400:
        print(f"  Warning: panning area too narrow, reducing scale bar width")
        scale_bar_width = max(60, viewport_width // 10)
        panning_width = viewport_width - scale_bar_width
    print(f"  Layout: scale_bar={scale_bar_width}px + panning={panning_width}px")

    # Legend
    legend_img = None
    legend_array = None
    legend_h = 0
    if legend_path and os.path.exists(legend_path):
        legend_img = Image.open(legend_path).convert("RGB")
        lw, lh = legend_img.size
        if lw != viewport_width:
            s = viewport_width / lw
            legend_img = legend_img.resize(
                (viewport_width, int(lh * s)), Image.Resampling.LANCZOS
            )
        legend_h = legend_img.size[1]
        if legend_h % 2 != 0:
            legend_h += 1
            padded = Image.new("RGB", (viewport_width, legend_h), background)
            padded.paste(legend_img, (0, 0))
            legend_img = padded
        legend_array = np.array(legend_img)
        print(f"  Legend:   {legend_img.size[0]} x {legend_img.size[1]}")

    # Ensure even dimensions for H.264
    total_h = viewport_height + legend_h
    if viewport_width % 2 != 0:
        viewport_width += 1
        panning_width = viewport_width - scale_bar_width
    if total_h % 2 != 0:
        total_h += 1
        legend_h = total_h - viewport_height

    total_frames = int(duration * fps)
    pan_start = max(0, content_start - 10)
    pan_end = content_end
    pan_distance = max(1, pan_end - pan_start)

    print(f"  Frames:   {total_frames}")
    print(f"  Max zoom: {max_zoom}")

    text_color = (255, 255, 255) if background == "black" else (0, 0, 0)
    bg_tuple = (0, 0, 0) if background == "black" else (255, 255, 255)
    content_padding = 10
    min_content_h = 20

    # For uniform zoom, crop width varies per frame based on zoom level
    # For vertical-only zoom, fixed_crop_w stays constant
    base_crop_w = panning_width  # Base horizontal extent at 1x zoom

    # Start ffmpeg encoder
    ffmpeg_cmd = [
        "ffmpeg", "-y",
        "-f", "rawvideo",
        "-pix_fmt", "rgb24",
        "-s", f"{viewport_width}x{total_h}",
        "-r", str(fps),
        "-i", "-",
        "-c:v", "libx264",
        "-preset", "medium",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        output_path,
    ]
    process = subprocess.Popen(ffmpeg_cmd, stdin=subprocess.PIPE, stderr=subprocess.PIPE)

    print(f"\nRendering {total_frames} frames …")
    last_pct = -1

    # Fixed y-position for read tops in viewport (small padding from top)
    reads_top_y = 20

    # Pre-load font and cache rotated labels for scale bar (big performance win!)
    scale_bar_font = _load_font(36)
    rotated_label_cache = {}

    for fidx in range(total_frames):
        t = fidx / max(1, total_frames - 1)

        # Content height at current x position (below top_margin)
        # Look ahead based on pan position to get content height
        x_preview = int(pan_start + t * pan_distance)
        ch = max(min_content_h, profile[min(x_preview, len(profile) - 1)])

        # Vertical zoom: scale content to fit in available viewport height
        available_height = viewport_height - reads_top_y
        v_zoom = min(available_height / (ch + content_padding), max_zoom)

        # Base horizontal zoom (for uniform zoom mode)
        h_zoom = v_zoom

        # Apply vertical zoom boost at start (allows truncating reads to see top detail)
        # Boost only affects vertical, not horizontal panning
        # top_bias=1 gives 100% boost at start (2x zoom), top_bias=2 gives 200% (3x), etc.
        if top_bias > 0:
            zoom_boost = (1 - t) * top_bias  # Full bias applied at start
            v_zoom = min(v_zoom * (1 + zoom_boost), max_zoom)

        # Calculate crop dimensions based on zoom mode
        if uniform_zoom:
            # Uniform zoom for horizontal, but vertical can be boosted
            crop_w = int(panning_width / h_zoom)
            crop_h = int(available_height / v_zoom)
        else:
            # Vertical-only zoom (legacy): horizontal stays 1:1
            crop_w = base_crop_w
            crop_h = int(available_height / v_zoom)

        # Source x position (left edge of panning viewport)
        # For uniform zoom, need to adjust pan position since we're showing less horizontal content
        x_pos = int(pan_start + t * pan_distance)
        x_pos = min(x_pos, img_w - crop_w)
        x_pos = max(0, x_pos)

        # Crop region in source - start at top_margin (where reads begin)
        # This anchors the TOP of reads at a fixed position
        crop_y0 = top_margin
        crop_y1 = min(crop_y0 + crop_h, img_h)

        crop_x0 = x_pos
        crop_x1 = min(crop_x0 + crop_w, img_w)

        crop = img_array[crop_y0:crop_y1, crop_x0:crop_x1]

        # Resize: both dimensions scaled by zoom factor (cv2 is ~5-10x faster)
        if crop.shape[0] > 0 and crop.shape[1] > 0:
            new_w = panning_width
            new_h = available_height
            if HAS_CV2:
                panning_arr = cv2.resize(crop, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
            else:
                panning_arr = np.array(Image.fromarray(crop).resize(
                    (new_w, new_h), Image.Resampling.BILINEAR
                ))
        else:
            panning_arr = np.full((available_height, panning_width, 3), bg_tuple, dtype=np.uint8)

        # Build frame directly in numpy (faster than PIL Image.new + paste)
        frame_arr = np.full((viewport_height, viewport_width, 3), bg_tuple, dtype=np.uint8)
        frame_arr[reads_top_y:reads_top_y + new_h, scale_bar_width:scale_bar_width + new_w] = panning_arr
        frame = Image.fromarray(frame_arr)

        # Draw scale bar flush against the panning content, aligned with reads top
        if ratio > 0:
            draw_ctx = ImageDraw.Draw(frame)
            bar_height = min(150, available_height - 20)

            # Physical length represented by bar_height viewport pixels
            source_px = bar_height / v_zoom
            bp = source_px / ratio
            nice_bp = _nice_scale_value(bp)

            # Actual visual height for the nice value
            actual_source_px = nice_bp * ratio
            actual_height = int(actual_source_px * v_zoom)
            actual_height = max(10, min(actual_height, available_height - 20))

            # Position: flush against right edge of scale bar area, TOP aligned with reads
            bar_x = scale_bar_width - 12
            bar_y = reads_top_y  # Align with top of reads

            # Vertical bar (thicker)
            draw_ctx.rectangle(
                [bar_x, bar_y, bar_x + 4, bar_y + actual_height], fill=text_color
            )
            # Ticks
            draw_ctx.line([(bar_x - 4, bar_y), (bar_x + 8, bar_y)], fill=text_color, width=2)
            draw_ctx.line(
                [(bar_x - 4, bar_y + actual_height), (bar_x + 8, bar_y + actual_height)],
                fill=text_color, width=2,
            )

            # Vertical label (rotated 90 degrees, large font)
            # Position: bottom of rotated text aligns with top of scale bar (right-aligned when reading vertically)
            label = f"{nice_bp // 1000} Kbp" if nice_bp >= 1000 else f"{nice_bp} bp"

            # Use cached rotated label or create new one
            if label not in rotated_label_cache:
                txt_img = Image.new("RGBA", (200, 50), (0, 0, 0, 0))
                txt_draw = ImageDraw.Draw(txt_img)
                bbox = txt_draw.textbbox((0, 0), label, font=scale_bar_font)
                txt_w = bbox[2] - bbox[0]
                txt_h = bbox[3] - bbox[1]
                # Right-align text so right edge becomes top after 90° rotation
                txt_draw.text((200 - txt_w, (50 - txt_h) // 2), label, fill=text_color + (255,), font=scale_bar_font)
                rotated_label_cache[label] = txt_img.rotate(90, expand=True)
            txt_rotated = rotated_label_cache[label]

            # Position: label right-aligned (top after rotation) to top of scale bar
            label_x = bar_x - 60  # Left of scale bar
            label_y = bar_y  # Align with top of scale bar
            frame.paste(txt_rotated, (label_x, label_y), txt_rotated)

        # Assemble output frame (panning + legend)
        frame_arr = np.array(frame)
        if legend_array is not None:
            out = np.empty((total_h, viewport_width, 3), dtype=np.uint8)
            out[:viewport_height] = frame_arr
            out[viewport_height:viewport_height + legend_array.shape[0]] = legend_array
            if viewport_height + legend_array.shape[0] < total_h:
                out[viewport_height + legend_array.shape[0]:] = bg_tuple
        else:
            out = frame_arr

        process.stdin.write(out.tobytes())

        pct = int(100 * fidx / total_frames)
        if pct != last_pct and pct % 5 == 0:
            last_pct = pct
            print(f"  {pct}%  (frame {fidx}/{total_frames})", flush=True)

    process.stdin.close()
    process.wait()

    if process.returncode != 0:
        stderr = process.stderr.read().decode()
        print(f"  ffmpeg error:\n{stderr[-500:]}")
        raise RuntimeError("ffmpeg encoding failed")

    fsize = os.path.getsize(output_path)
    print(f"\n  Saved: {output_path}")
    print(f"  Size:  {fsize / 1024 / 1024:.1f} MB")
    return output_path


# ─── Fixed-zoom panning (original) ──────────────────────────────────────────

def create_horizontal_panning(
    input_path, output_path, duration, fps, crop_ratio,
    viewport_width, viewport_height,
    scale_bar_path, legend_path, background, scale_bar_padding,
):
    """Seamless horizontal panning animation (fixed zoom)."""

    print("Creating horizontal panning animation (fixed zoom)")
    print(f"  Input:    {input_path}")
    print(f"  Output:   {output_path}")
    print(f"  Duration: {duration:.1f}s  FPS: {fps}")

    img = Image.open(input_path)
    orig_width, orig_height = img.size
    print(f"  Original size: {orig_width} x {orig_height}")

    # Crop to top portion
    crop_height = int(orig_height * crop_ratio)
    img_cropped = img.crop((0, 0, orig_width, crop_height))
    print(f"  Cropped to top {crop_ratio*100:.0f}%: {orig_width} x {crop_height}")

    # Scale to viewport height
    scale_factor = viewport_height / crop_height
    scaled_width = int(orig_width * scale_factor)
    img_scaled = img_cropped.resize(
        (scaled_width, viewport_height), Image.Resampling.LANCZOS
    )
    print(f"  Scaled to viewport height: {scaled_width} x {viewport_height}")

    # Seamless tile
    tiled_width = scaled_width * 2
    img_tiled = Image.new("RGB", (tiled_width, viewport_height), background)
    img_tiled.paste(img_scaled, (0, 0))
    img_tiled.paste(img_scaled, (scaled_width, 0))
    print(f"  Tiled for seamless loop: {tiled_width} x {viewport_height}")

    temp_files = []
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tiled_path = tmp.name
        temp_files.append(tiled_path)
        img_tiled.save(tiled_path, "PNG")

    pan_distance = scaled_width
    total_frames = int(duration * fps)
    px_per_frame = pan_distance / total_frames

    print(f"  Pan distance: {pan_distance}px over {total_frames} frames")
    print(f"  Speed: {px_per_frame:.2f} px/frame")

    # ffmpeg filter chain
    filter_parts = []
    inputs = ["-loop", "1", "-i", tiled_path]
    input_idx = 0

    crop_filter = (
        f"[{input_idx}:v]crop={viewport_width}:{viewport_height}:"
        f"'mod(t*{pan_distance}/{duration},iw-{viewport_width})':0[panning]"
    )
    filter_parts.append(crop_filter)
    last_stream = "panning"
    input_idx += 1

    if scale_bar_path and os.path.exists(scale_bar_path):
        inputs.extend(["-i", scale_bar_path])
        overlay_filter = (
            f"[{last_stream}][{input_idx}:v]overlay="
            f"{scale_bar_padding}:{scale_bar_padding}[with_scale]"
        )
        filter_parts.append(overlay_filter)
        last_stream = "with_scale"
        input_idx += 1
        print(f"  Adding scale bar: {scale_bar_path}")

    if legend_path and os.path.exists(legend_path):
        with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
            panning_video_path = tmp.name
            temp_files.append(panning_video_path)

        filter_complex = ";".join(filter_parts)
        run_ffmpeg([
            "ffmpeg", "-y", *inputs,
            "-filter_complex", filter_complex,
            "-map", f"[{last_stream}]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            panning_video_path,
        ])

        legend_img = Image.open(legend_path)
        lw, lh = legend_img.size
        if lw != viewport_width:
            s = viewport_width / lw
            legend_img = legend_img.resize(
                (viewport_width, int(lh * s)), Image.Resampling.LANCZOS
            )

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            legend_scaled_path = tmp.name
            temp_files.append(legend_scaled_path)
            legend_img.save(legend_scaled_path, "PNG")

        run_ffmpeg([
            "ffmpeg", "-y",
            "-i", panning_video_path,
            "-loop", "1", "-i", legend_scaled_path,
            "-filter_complex", "[0:v][1:v]vstack=inputs=2[out]",
            "-map", "[out]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            output_path,
        ])
    else:
        filter_complex = ";".join(filter_parts)
        run_ffmpeg([
            "ffmpeg", "-y", *inputs,
            "-filter_complex", filter_complex,
            "-map", f"[{last_stream}]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            output_path,
        ])

    for f in temp_files:
        if os.path.exists(f):
            os.unlink(f)

    fsize = os.path.getsize(output_path)
    print(f"  Saved: {output_path}")
    print(f"  File size: {fsize / 1024 / 1024:.1f} MB")
    return output_path


def create_vertical_panning(
    input_path, output_path, duration, fps,
    viewport_width, viewport_height,
    scale_bar_path, legend_path, background, scale_bar_padding,
):
    """Seamless vertical panning animation (fixed zoom)."""

    print("Creating vertical panning animation (fixed zoom)")
    print(f"  Input:    {input_path}")
    print(f"  Output:   {output_path}")
    print(f"  Duration: {duration:.1f}s  FPS: {fps}")

    img = Image.open(input_path)
    orig_width, orig_height = img.size
    print(f"  Original size: {orig_width} x {orig_height}")

    scale_factor = viewport_width / orig_width
    scaled_height = int(orig_height * scale_factor)
    img_scaled = img.resize(
        (viewport_width, scaled_height), Image.Resampling.LANCZOS
    )
    print(f"  Scaled to viewport width: {viewport_width} x {scaled_height}")

    min_tiled_height = viewport_height + scaled_height
    num_tiles = max(2, (min_tiled_height // scaled_height) + 1)
    tiled_height = scaled_height * num_tiles
    img_tiled = Image.new("RGB", (viewport_width, tiled_height), background)
    for i in range(num_tiles):
        img_tiled.paste(img_scaled, (0, i * scaled_height))
    print(f"  Tiled: {viewport_width} x {tiled_height} ({num_tiles} tiles)")

    temp_files = []
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tiled_path = tmp.name
        temp_files.append(tiled_path)
        img_tiled.save(tiled_path, "PNG")

    pan_distance = scaled_height
    total_frames = int(duration * fps)
    px_per_frame = pan_distance / total_frames

    print(f"  Pan distance: {pan_distance}px over {total_frames} frames")
    print(f"  Speed: {px_per_frame:.2f} px/frame")

    filter_parts = []
    inputs = ["-loop", "1", "-i", tiled_path]
    input_idx = 0

    crop_filter = (
        f"[{input_idx}:v]crop={viewport_width}:{viewport_height}:"
        f"0:'mod(t*{pan_distance}/{duration},{pan_distance})'[panning]"
    )
    filter_parts.append(crop_filter)
    last_stream = "panning"
    input_idx += 1

    if scale_bar_path and os.path.exists(scale_bar_path):
        inputs.extend(["-i", scale_bar_path])
        overlay_filter = (
            f"[{last_stream}][{input_idx}:v]overlay="
            f"{scale_bar_padding}:{scale_bar_padding}[with_scale]"
        )
        filter_parts.append(overlay_filter)
        last_stream = "with_scale"
        input_idx += 1
        print(f"  Adding scale bar: {scale_bar_path}")

    if legend_path and os.path.exists(legend_path):
        with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
            panning_video_path = tmp.name
            temp_files.append(panning_video_path)

        filter_complex = ";".join(filter_parts)
        run_ffmpeg([
            "ffmpeg", "-y", *inputs,
            "-filter_complex", filter_complex,
            "-map", f"[{last_stream}]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            panning_video_path,
        ])

        legend_img = Image.open(legend_path)
        lw, lh = legend_img.size
        if lh != viewport_height:
            s = viewport_height / lh
            legend_img = legend_img.resize(
                (int(lw * s), viewport_height), Image.Resampling.LANCZOS
            )

        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            legend_scaled_path = tmp.name
            temp_files.append(legend_scaled_path)
            legend_img.save(legend_scaled_path, "PNG")

        run_ffmpeg([
            "ffmpeg", "-y",
            "-i", panning_video_path,
            "-loop", "1", "-i", legend_scaled_path,
            "-filter_complex", "[0:v][1:v]hstack=inputs=2[out]",
            "-map", "[out]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            output_path,
        ])
    else:
        filter_complex = ";".join(filter_parts)
        run_ffmpeg([
            "ffmpeg", "-y", *inputs,
            "-filter_complex", filter_complex,
            "-map", f"[{last_stream}]",
            "-t", str(int(duration)),
            "-r", str(fps),
            "-c:v", "libx264", "-preset", "medium", "-crf", "18",
            "-pix_fmt", "yuv420p",
            output_path,
        ])

    for f in temp_files:
        if os.path.exists(f):
            os.unlink(f)

    fsize = os.path.getsize(output_path)
    print(f"  Saved: {output_path}")
    print(f"  File size: {fsize / 1024 / 1024:.1f} MB")
    return output_path


# ─── Utilities ───────────────────────────────────────────────────────────────

def run_ffmpeg(cmd):
    """Run ffmpeg with error handling."""
    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
    except subprocess.CalledProcessError as e:
        print(f"  ffmpeg error: {e.stderr[-500:]}")
        raise


# ─── CLI ─────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Create panning animations from wide/tall images",
        formatter_class=argparse.RawTextHelpFormatter,
    )

    # Input / output
    p.add_argument("--input", "-i", required=True,
                   help="Input PNG image (use plot_reads.py --format png to generate)")
    p.add_argument("--output", "-o", required=True,
                   help="Output MP4 video")
    p.add_argument("--direction", choices=["horizontal", "vertical"],
                   default="horizontal", help="Panning direction (default: horizontal)")

    # Duration
    dur = p.add_argument_group("duration (choose one)")
    dur.add_argument("--duration", "-d", type=float, default=None,
                     help="Fixed duration in seconds")
    dur.add_argument("--num-reads", type=int, default=None,
                     help="Number of reads in the image (for auto-duration)")
    dur.add_argument("--reads-per-second", type=float, default=20.625,
                     help="Target reads/s scroll rate (default: 20.625)")

    # Zoom
    zm = p.add_argument_group("zoom mode")
    zm.add_argument("--zoom", choices=["fixed", "adaptive"], default="fixed",
                    help="Zoom mode (default: fixed)")
    zm.add_argument("--crop-ratio", type=float, default=0.5,
                    help="Height crop ratio, fixed zoom only (default: 0.5)")
    zm.add_argument("--max-zoom", type=float, default=None,
                    help="Max zoom factor, adaptive only (default: auto from scale-bar-max-bp)")
    zm.add_argument("--scale-bar-max-bp", type=int, default=20000,
                    help="Target bp for scale bar at max zoom (default: 20000 = 20kb)")
    zm.add_argument("--scale-bar-fraction", type=float, default=0.1,
                    help="Fraction of viewport height for scale bar at max zoom (default: 0.1 = 10%%)")
    zm.add_argument("--top-bias", type=float, default=0.0,
                    help="Non-linear bias toward top of reads (0=linear, 1=sqrt, 2=more biased). "
                         "Higher values spend more time zoomed in at the top.")
    zm.add_argument("--top-margin", type=int, default=80,
                    help="Source image top margin px (default: 80, from plot_reads)")
    zm.add_argument("--left-margin", type=int, default=60,
                    help="Source image left margin px (default: 60, from plot_reads)")
    zm.add_argument("--ratio", type=float, default=1 / 300,
                    help="bp-to-pixel ratio in source (default: 1/300)")
    zm.add_argument("--scale-bar-width", type=int, default=100,
                    help="Width of scale bar area in output px (default: 100)")
    zm.add_argument("--zoom-smoothing", type=int, default=200,
                    help="Zoom smoothing window size (0=none, default: 200)")
    zm.add_argument("--uniform-zoom", action="store_true", default=True,
                    help="Zoom both dimensions uniformly (default: True)")
    zm.add_argument("--vertical-only-zoom", action="store_true",
                    help="Only zoom vertically (legacy behavior)")

    # Viewport
    p.add_argument("--viewport-width", type=int, default=None,
                   help="Viewport width px (default: 1920 horiz, 640 vert)")
    p.add_argument("--viewport-height", type=int, default=None,
                   help="Viewport height px (default: 1080 horiz, 864 vert)")
    p.add_argument("--fps", type=int, default=30,
                   help="Frames per second (default: 30)")

    # Overlays
    p.add_argument("--scale-bar", type=str, default=None,
                   help="Static scale bar PNG overlay (fixed zoom only)")
    p.add_argument("--legend", type=str, default=None,
                   help="Legend image (PNG or SVG) below/beside panning area")
    p.add_argument("--background", default="black",
                   help="Background colour (default: black)")
    p.add_argument("--scale-bar-padding", type=int, default=10,
                   help="Padding around scale bar/overlays (default: 10)")

    return p.parse_args()


def main():
    args = parse_args()

    # ── Resolve duration ──────────────────────────────────────────────────
    if args.num_reads:
        duration = args.num_reads / args.reads_per_second
        print(f"Auto-duration: {args.num_reads} reads / {args.reads_per_second} reads·s⁻¹"
              f" = {duration:.1f}s ({duration / 60:.1f} min)")
    elif args.duration:
        duration = args.duration
    else:
        duration = 60
        print("No --duration or --num-reads given; using default 60s")

    # ── Validate PNG input ─────────────────────────────────────────────────
    if not args.input.lower().endswith(".png"):
        raise ValueError(
            f"Input must be a PNG file, got: {args.input}\n"
            "Use KaryoScope_plot_reads.py --format png to generate PNG input."
        )
    input_path = args.input

    # Determine viewport width early for legend scaling
    if args.zoom == "adaptive" and args.direction == "horizontal":
        viewport_width = args.viewport_width or 1920
    elif args.direction == "horizontal":
        viewport_width = args.viewport_width or 1920
    else:
        viewport_width = args.viewport_width or 640

    # Convert legend SVG to PNG if needed (small SVGs work fine with rsvg-convert)
    temp_files = []
    legend_path = args.legend
    if legend_path:
        legend_path, leg_is_temp, _ = ensure_png(legend_path, svg_width=viewport_width)
        if leg_is_temp:
            temp_files.append(legend_path)

    scale_bar_path = args.scale_bar
    if scale_bar_path:
        scale_bar_path, sb_is_temp, _ = ensure_png(scale_bar_path)
        if sb_is_temp:
            temp_files.append(scale_bar_path)

    # ── Dispatch ──────────────────────────────────────────────────────────
    try:
        if args.zoom == "adaptive" and args.direction == "horizontal":
            viewport_width = args.viewport_width or 1920
            viewport_height = args.viewport_height or 1080

            # Determine zoom mode: uniform by default, vertical-only if explicitly requested
            uniform_zoom = not args.vertical_only_zoom

            # Calculate max_zoom from scale bar parameters if not explicitly set
            # Formula: at max_zoom, scale_bar_max_bp should fill scale_bar_fraction of viewport
            # scale_bar_height_px = scale_bar_max_bp * ratio * max_zoom
            # scale_bar_height_px = available_height * scale_bar_fraction
            # => max_zoom = (available_height * scale_bar_fraction) / (scale_bar_max_bp * ratio)
            reads_top_y = 20  # Fixed padding from top
            available_height = viewport_height - reads_top_y
            if args.max_zoom is not None:
                max_zoom = args.max_zoom
            else:
                scale_bar_source_px = args.scale_bar_max_bp * args.ratio
                target_height_px = available_height * args.scale_bar_fraction
                max_zoom = target_height_px / scale_bar_source_px
                print(f"  Auto max_zoom: {max_zoom:.2f} ({args.scale_bar_max_bp}bp @ {args.scale_bar_fraction*100:.0f}% viewport)")

            create_adaptive_horizontal_panning(
                input_path=input_path,
                output_path=args.output,
                duration=duration,
                fps=args.fps,
                viewport_width=viewport_width,
                viewport_height=viewport_height,
                legend_path=legend_path,
                background=args.background,
                top_margin=args.top_margin,
                left_margin=args.left_margin,
                ratio=args.ratio,
                max_zoom=max_zoom,
                scale_bar_padding=args.scale_bar_padding,
                scale_bar_width=args.scale_bar_width,
                zoom_smoothing=args.zoom_smoothing,
                uniform_zoom=uniform_zoom,
                top_bias=args.top_bias,
            )
        elif args.direction == "horizontal":
            viewport_width = args.viewport_width or 1920
            viewport_height = args.viewport_height or 432

            create_horizontal_panning(
                input_path=input_path,
                output_path=args.output,
                duration=duration,
                fps=args.fps,
                crop_ratio=args.crop_ratio,
                viewport_width=viewport_width,
                viewport_height=viewport_height,
                scale_bar_path=scale_bar_path,
                legend_path=legend_path,
                background=args.background,
                scale_bar_padding=args.scale_bar_padding,
            )
        else:  # vertical
            viewport_width = args.viewport_width or 640
            viewport_height = args.viewport_height or 864

            create_vertical_panning(
                input_path=input_path,
                output_path=args.output,
                duration=duration,
                fps=args.fps,
                viewport_width=viewport_width,
                viewport_height=viewport_height,
                scale_bar_path=scale_bar_path,
                legend_path=legend_path,
                background=args.background,
                scale_bar_padding=args.scale_bar_padding,
            )
    finally:
        # Clean up temp PNG conversions
        for f in temp_files:
            if os.path.exists(f):
                os.unlink(f)

    print("\nDone!")


if __name__ == "__main__":
    main()
